FROM nginx:latest

ARG PORT
ARG MINIO_HOST
ARG RENDER_EXTERNAL_HOSTNAME
COPY ./nginx.template ./
#this version escapes
RUN curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst \
  && chmod +x envsubst \
  && mv envsubst /usr/local/bin
RUN envsubst < nginx.template > /etc/nginx/conf.d/default.conf
