services:
  - type: web
    name: minio-main
    healthCheckPath: /minio/health/live
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    disk:
      name: data
      mountPath: /data
    envVars:
      - key: MINIO_ROOT_USER
        generateValue: true
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: 10000,9000
  - type: web
    name: minio-proxy
    healthCheckPath: /health
    env: docker
    dockerfilePath: ./Dockerfile.proxy
    dockerContext: . 
    envVars:
      - key: MINIO_HOST
        fromService:
          type: web
          name: minio-main
          property: host
      - key: PORT
        value: 10000
